---
test1:
  check_interval: 1
  backend_mode: "active_passive"
  scheduler: wrr
  fwmark: 1
  ramp_up_time: 120
  has_downpage: true
  nagios:
    server: nsca.host
    check: test1_status
    host: prod-load
  nodes:
  - address: 127.0.0.1
    port: 9001
    path: /test/valid
    priority: 0
  - address: 127.0.0.1
    port: 9002
    path: /test/valid
    priority: 1
test2:
  check_interval: 2
  scheduler: wrr
  fwmark: 2
  nodes:
  - address: 127.0.0.1
    port: 9001
    path: /test/invalid
  - address: 127.0.0.1
    port: 9002
    path: /test/invalid
test3:
  check_interval: 1
  scheduler: wrr
  fwmark: 3
  nodes:
  - address: 127.0.0.1
    port: 9001
    path: /test/valid
  - address: 127.0.0.1
    port: 9002
    path: /test/invalid
